### ISSUE TITLE
Feature: Inclusion of Management Group Scope

### ISSUE THREAD

**Issue by glloyd2010f** [Azure/policy-compliance-scan#22]
The addition to run this against a Management Group instead of the subscription, resource groups, or resource scopes.

**Comment by Josh-01** [comment]
Hi @glloyd2010f,  
 
Azure currently does not support triggering a scan against an entire Management group, so this feature request cannot be picked up for now.

Thanks.

**Comment by JustinGrote** [comment]
@Josh-01 this could be implemented by querying the management groups and generating a list of scoped subscriptions and then passing that to the action. Rather than having to do this work outside the function, why not just add this functionality?
