### ISSUE TITLE
Unable to use policy-assignments-ignore argument

### ISSUE THREAD

**Issue by bajmming** [Azure/policy-compliance-scan#38]
When I try to use the _policy-assignments-ignore_ argument I get the warning below...

> Warning: Unexpected input(s) 'policy-assignments-ignore', valid inputs are ['scopes', 'scopes-ignore', 'wait', 'skip-report', 'report-name'] 

and the scan does not ignore the policy.  Has this change been released into Github for everyone to use or has only the code been updated...or am I just using it wrong?

The end of my action yaml is below with the guids removed...
```
uses: azure/policy-compliance-scan@v0
with:
        scopes: |
          /subscriptions/this-guid-has-been-removed
        policy-assignments-ignore: |
          /subscriptions/this-guid-has-been-removed/providers/Microsoft.Authorization/policyAssignments/SecurityCenterBuiltIn
```

**Comment by Josh-01** [comment]
Thank you for pointing this out! Working on fixing this.

**Comment by Josh-01** [comment]
Hi @bajmming ,
I have pushed in the fix - your usage was correct.
Could you please let me know if this works for you now ?

**Comment by bajmming** [comment]
All working now...thanks for sorting it out so quickly :)
